version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci
      - node/test:
          filters:
            branches:
              only:
                - circleci